# Final Exam 29-32 Weekends

1. write function to return two result of odd and even num of list below
    - list of values from 20-100
    - [2,4,6,8,9,10]
    - [1,2,3,5,7,9]
    - [0]
    - [1]

In [471]:
def separate_odd_even(lst):
    odd_nums = []
    even_nums = []
    for num in lst:
        if num % 2 == 0:
            even_nums.append(num)
        else:
            odd_nums.append(num)
    return odd_nums, even_nums

test_lists = [
    list(range(20, 101)),
    [2, 4, 6, 8, 9, 10],
    [1, 2, 3, 5, 7, 9],
    [0],
    [1]
]

for test_list in test_lists:
    odd, even = separate_odd_even(test_list)
    print("List:", test_list)
    print("Odd numbers:", odd)
    print("Even numbers:", even)
    print()

List: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
Odd numbers: [21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
Even numbers: [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]

List: [2, 4, 6, 8, 9, 10]
Odd numbers: [9]
Even numbers: [2, 4, 6, 8, 10]

List: [1, 2, 3, 5, 7, 9]
Odd numbers: [1, 3, 5, 7, 9]
Even numbers: [2]

List: [0]
Odd numbers: []
Even numbers: [0]

List: [1]
Odd numbers: [1]
Even numbers: []



2. write function to reverse string below
    - James => semaJ
    - Cambodia => aidobmaC
    - National University of Management => tnemeganaM fo ytisrevinU lanoitaN

In [472]:
def reverse_string(s):
    return s[::-1]

test_strings = [
    "James",
    "Cambodia",
    "National University of Management"
]

for test_string in test_strings:
    print(test_string, "=>", reverse_string(test_string))


James => semaJ
Cambodia => aidobmaC
National University of Management => tnemeganaM fo ytisrevinU lanoitaN


3. write function to generate list of value below
    - All odd number from 20-100
    - All Even number from 20-100
    - All Prime number from 20-100
    - All can divid by 5 from 20-100

In [473]:
def generate_odd_numbers(start, end):
    return [num for num in range(start, end + 1) if num % 2 != 0]

def generate_even_numbers(start, end):
    return [num for num in range(start, end + 1) if num % 2 == 0]

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

def generate_prime_numbers(start, end):
    return [num for num in range(start, end + 1) if is_prime(num)]

def generate_divisible_by_5(start, end):
    return [num for num in range(start, end + 1) if num % 5 == 0]

start = 20
end = 100

print("Odd numbers from 20 to 100:", generate_odd_numbers(start, end))
print("Even numbers from 20 to 100:", generate_even_numbers(start, end))
print("Prime numbers from 20 to 100:", generate_prime_numbers(start, end))
print("Numbers divisible by 5 from 20 to 100:", generate_divisible_by_5(start, end))

Odd numbers from 20 to 100: [21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
Even numbers from 20 to 100: [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
Prime numbers from 20 to 100: [23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
Numbers divisible by 5 from 20 to 100: [20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


4. write function to get middle of string and revease of length is even number
    - ABCDEF => DC
    - ABCDE => C

In [474]:
def middle_and_reverse(s):
    length = len(s)
    middle_index = length // 2
    
    if length % 2 == 0:
        return s[middle_index - 1::-1]
    else:
        return s[middle_index]

test_strings = [
    "ABCDEF",
    "ABCDE"
]

for test_string in test_strings:
    print(test_string, "=>", middle_and_reverse(test_string))


ABCDEF => CBA
ABCDE => C


5. write function to add value to middle of string if length of string is even and otherwise remove value in the middle
    - NUM => NM
    - NUME => NUAME

In [475]:
def modify_middle(s, value):
    length = len(s)
    middle_index = length // 2

    if length % 2 == 0:
        return s[:middle_index] + value + s[middle_index:]
    else:
        return s[:middle_index] + s[middle_index+1:]

test_strings = [
    "NUM",
    "NUME"
]
value = "A" 

for test_string in test_strings:
    print(test_string, "=>", modify_middle(test_string, value))


NUM => NM
NUME => NUAME


# Working with Numpy Array

1. create numpy array of 100 values with 0

In [476]:
import numpy as np

array = np.zeros(100)

print(array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


2. create numpy array of 100 values with 1

In [477]:
import numpy as np

array = np.ones(100)

print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


3. create numpy array of 100 values with 7

In [478]:
import numpy as np

array = np.full(100, 7)

print(array)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


4. create numpy array of value range from 20-100

In [479]:
import numpy as np

array = np.arange(20, 101)

print(array)

[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100]


5. create numpy array of identity 5x5

In [480]:
import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


6. resahpe below array to 5x3

In [481]:
import numpy as np

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [482]:
import numpy as np

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

reshaped_array = np.reshape(array, (5, 3))

print(reshaped_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


7. slicing array

In [4]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20,],
                  [21, 22, 23, 24, 25]])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


8. slicing array

In [10]:
import numpy as np

array = np.array([[2],
                  [7],
                  [12],
                  [17],
                  [22]])
print("array")
print(array)      

array
[[ 2]
 [ 7]
 [12]
 [17]
 [22]]


9. slicing array

In [20]:
import numpy as np

array = np.array([[7, 8, 9]])
print("array", array)

array [[7 8 9]]


10. slicing array and transpose 

In [22]:
import numpy as np

arr = np.array([[7, 12, 17]])

transposed_arr = arr.T
print("Transposed array:")
print(transposed_arr)


Transposed array:
[[ 7]
 [12]
 [17]]


11. slicing array and revease

In [26]:
import numpy as np

arr = np.array([[15, 14, 13, 12, 11]])

print("array",arr)


array [[15 14 13 12 11]]


12. slicing array

In [36]:
import numpy as np

arr = np.array([[7, 8, 9],
                [12, 13, 14],
                [17, 18, 19]])

sliced_arr = arr[0:2, 1:]

print("Sliced array:")
print(sliced_arr)


Sliced array:
[[ 8  9]
 [13 14]]


13. create numpy array 10x10 with random value

In [485]:
import numpy as np

array = np.random.randint(0, 101, size=(10, 10))

print(array)


[[  3  43  89  49  91  80   7  71  36  93]
 [ 53  36  26  44   7  85  11  63  80  86]
 [ 75  90  50  87  61  38  21  23  80  69]
 [ 48   9  43 100  53  83  26  19  61  65]
 [ 92  27  83  30   6  29  33  58   3  64]
 [ 49  60  21  15  80   5  29  66  95  63]
 [ 45  57  76  16  36  12  34   3  86  68]
 [  7  33  29  81  56  94  80  72  91  35]
 [  6  17  92  21  24  43  35  45  80  78]
 [ 81  14  44   8  91  46  88  27  70  82]]


14. create two numpy array and multiply
    - a : numpy array must range from 1-10
    - b : numpy array must range from 11-20

In [486]:
import numpy as np

a = np.arange(1, 10).reshape(3, 3)

b = np.arange(11, 20).reshape(3, 3)

result = np.dot(a,b)

print("Result of element-wise multiplication:")
print(result)

Result of element-wise multiplication:
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


15. Create three dimension numpy array below

In [487]:
import numpy as np

array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                     
                     [[7, 8, 9],
                      [10, 11, 12]]])

print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
