# Final Exam 29-32 Weekends

# Phak Mengheang

1. write function to return two result of odd and even num of list below
    - list of values from 20-100
    - [2,4,6,8,9,10]
    - [1,2,3,5,7,9]
    - [0]
    - [1]

In [10]:
test_lists = [
    list(range(20, 101)),
    [2, 4, 6, 8, 9, 10],
    [1, 2, 3, 5, 7, 9],
    [0],
    [1]
]
def getOddEvenFromList(lst):
    odd_numbers = []
    even_numbers = []
    for num in lst:
        if num % 2 == 0:
            even_numbers.append(num)
        else:
            odd_numbers.append(num)
    return odd_numbers, even_numbers

for test_list in test_lists:
    odd, even = getOddEvenFromList(test_list)
    print(f"List: {test_list}")
    print(f"Odd: {odd}")
    print(f"Even: {even}")
    print()

List: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
Odd: [21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
Even: [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]

List: [2, 4, 6, 8, 9, 10]
Odd: [9]
Even: [2, 4, 6, 8, 10]

List: [1, 2, 3, 5, 7, 9]
Odd: [1, 3, 5, 7, 9]
Even: [2]

List: [0]
Odd: []
Even: [0]

List: [1]
Odd: [1]
Even: []



2. write function to reverse string below
    - James => semaJ
    - Cambodia => aidobmaC
    - National University of Management => tnemeganaM fo ytisrevinU lanoitaN

In [11]:
test_strings = [
    "James",
    "Cambodia",
    "National University of Management"
]

def getReverseString(st):
    return st[::-1]

for test_string in test_strings:
    print(f"String: {test_string}")
    print(f"Reversed: {getReverseString(test_string)}")
    print()

String: James
Reversed: semaJ

String: Cambodia
Reversed: aidobmaC

String: National University of Management
Reversed: tnemeganaM fo ytisrevinU lanoitaN



3. write function to generate list of value below
    - All odd number from 20-100
    - All Even number from 20-100
    - All Prime number from 20-100
    - All can divid by 5 from 20-100

In [12]:
def doGenerateValues(lst):
    results = []
    for criteria in lst:
        if criteria == "odd":
            results.append([num for num in range(20, 101) if num % 2 != 0])
        elif criteria == "even":
            results.append([num for num in range(20, 101) if num % 2 == 0])
        elif criteria == "prime":
            def is_prime(n):
                if n <= 1:
                    return False
                if n <= 3:
                    return True
                if n % 2 == 0 or n % 3 == 0:
                    return False
                i = 5
                while i * i <= n:
                    if n % i == 0 or n % (i + 2) == 0:
                        return False
                    i += 6
                return True

            results.append([num for num in range(20, 101) if is_prime(num)])
        elif criteria == "divisible_by_5":
            results.append([num for num in range(20, 101) if num % 5 == 0])
        else:
            results.append([])
    return results

# Test the function
criteria_list = ["odd", "even", "prime", "divisible_by_5"]
generated_values = doGenerateValues(criteria_list)

# Print the results nicely formatted
for i, criteria in enumerate(criteria_list):
    print(f"{criteria.capitalize()} Numbers from 20 to 100:")
    print(generated_values[i])
    print()

Odd Numbers from 20 to 100:
[21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]

Even Numbers from 20 to 100:
[20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]

Prime Numbers from 20 to 100:
[23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]

Divisible_by_5 Numbers from 20 to 100:
[20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]



4. write function to get middle of string and revease of length is even number
    - ABCDEF => DC
    - ABCDE => C

In [13]:
def getMiddleString(st):
    length = len(st)
    middle_index = length // 2
    
    if length % 2 == 0:  
        return st[middle_index - 1:middle_index + 1][::-1]
    else:  
        return st[middle_index]


test_strings = ["ABCDEF", "ABCDE"]

for test_str in test_strings:
    print(f"{test_str} => {getMiddleString(test_str)}")


ABCDEF => DC
ABCDE => C


5. write function to add value to middle of string if length of string is even and otherwise remove value in the middle
    - NUM => NM
    - NUME => NUAME

In [14]:
def addValueToMiddle(value):
    input_str = "NUME"  
    length = len(input_str)
    middle_index = length // 2
    
    if length % 2 == 0:  
        return input_str[:middle_index] + value + input_str[middle_index:]
    else:  
        return input_str[:middle_index] + value + input_str[middle_index:]

# Test the function
value_to_add = "A"
print(addValueToMiddle(value_to_add))


NUAME


# Working with Numpy Array

1. create numpy array of 100 values with 0

In [15]:

import numpy as np
np.zeros(100)



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. create numpy array of 100 values with 1

In [16]:
import numpy as np

np.ones(100)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3. create numpy array of 100 values with 7

In [17]:
import numpy as np

np.full(100, 7)



array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

4. create numpy array of value range from 20-100

In [18]:
import numpy as np
np.arange(20, 101)



array([ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
        33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
        46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
        59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100])

5. create numpy array of identity 5x5

In [19]:

import numpy as np

np.eye(5)



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

6. resahpe below array to 5x3

In [20]:
import numpy as np

original_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

print(original_array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
reshaped_array = original_array.reshape(5, 3)

print(reshaped_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


7. slicing array

In [22]:
import numpy as np

given_array = np.array([[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10],
                        [11, 12, 13, 14, 15],
                        [16, 17, 18, 19, 20],
                        [21, 22, 23, 24, 25]])
print(given_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


8. slicing array

In [23]:
sliced_array = given_array[:, 1:2]

print(sliced_array)


[[ 2]
 [ 7]
 [12]
 [17]
 [22]]


9. slicing array

In [24]:
sliced_array = given_array[1:2, 1:4]

print(sliced_array)

[[7 8 9]]


10. slicing array and transpose 

In [35]:
sliced_array = given_array[1:4, 1:2].flatten()
print(sliced_array)

[ 7 12 17]


11. slicing array and revease

In [26]:
sliced_and_reversed_array = given_array[2:3, ::-1]
print(sliced_and_reversed_array)

[[15 14 13 12 11]]


12. slicing array

In [27]:
sliced_array = given_array[1:4, 1:4]
print(sliced_array)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


13. create numpy array 10x10 with random value

In [28]:
random_array = np.random.randint(0, 101, (10, 10))

print(random_array)

[[ 2 11 86 14 52 68 57 27 43 17]
 [22 96  5 38 21 11  7 87 56 24]
 [35 73 87 76 63 29 92 52 38 46]
 [24 89  9 61 14 47 96 68 85 68]
 [30 87 24 21 49  2 86  5 54 28]
 [61 89  2 14 24 49 56 53 38 77]
 [51 61 46 62 62 93 59 92  8 94]
 [92 18 25 73 75 13 21 59 25 34]
 [59 63 99 81 69 62 92 37 19  4]
 [34 73 77 19 52 12 66  0 72 77]]


14. create two numpy array and multiply
    - a : numpy array must range from 1-10
    - b : numpy array must range from 11-20

In [34]:

a = np.arange(1, 10).reshape(3,3)
b = np.arange(11, 20).reshape(3,3) 

answer = np.dot(a, b)
print(answer)



[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [33]:
given_array[:, 1:2].flatten()


array([ 2,  7, 12, 17, 22])

15. Create three dimension numpy array below

In [31]:
np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])