# Final Exam 29-32 Weekends

1. write function to return two result of odd and even num of list below
    - list of values from 20-100
    - [2,4,6,8,9,10]
    - [1,2,3,5,7,9]
    - [0]
    - [1]

In [4]:
def getOddEvenFromList(lst):
    odd_numbers = []
    even_numbers = []
    for num in lst:
        if num % 2 == 0:
            even_numbers.append(num)
        else:
            odd_numbers.append(num)
    return odd_numbers, even_numbers

test_lists = [
    [2, 4, 6, 8, 9, 10],
    [1, 2, 3, 5, 7, 9],
    [0],
    [1]
]

for test_list in test_lists:
    odd, even = getOddEvenFromList(test_list)
    print("Odd numbers:", odd)
    print("Even numbers:", even)
    print()
    print()


Odd numbers: [9]
Even numbers: [2, 4, 6, 8, 10]


Odd numbers: [1, 3, 5, 7, 9]
Even numbers: [2]


Odd numbers: []
Even numbers: [0]


Odd numbers: [1]
Even numbers: []




2. write function to reverse string below
    - James => semaJ
    - Cambodia => aidobmaC
    - National University of Management => tnemeganaM fo ytisrevinU lanoitaN

In [43]:
test_strings = [
    "James",
    "Cambodia",
    "National University of Management"
]

def getReverseString(st):
    return st[::-1]

for test_string in test_strings:
    print(f"String: {test_string}")
    print(f"Reversed: {getReverseString(test_string)}")

String: James
Reversed: semaJ
String: Cambodia
Reversed: aidobmaC
String: National University of Management
Reversed: tnemeganaM fo ytisrevinU lanoitaN


3. write function to generate list of value below
    - All odd number from 20-100
    - All Even number from 20-100
    - All Prime number from 20-100
    - All can divid by 5 from 20-100

In [44]:
def doGenerateValues(lst):
    results = []
    for criteria in lst:
        if criteria == "odd":
            results.append([num for num in range(20, 101) if num % 2 != 0])
        elif criteria == "even":
            results.append([num for num in range(20, 101) if num % 2 == 0])
        elif criteria == "prime":
            def is_prime(n):
                if n <= 1:
                    return False
                if n <= 3:
                    return True
                if n % 2 == 0 or n % 3 == 0:
                    return False
                i = 5
                while i * i <= n:
                    if n % i == 0 or n % (i + 2) == 0:
                        return False
                    i += 6
                return True

            results.append([num for num in range(20, 101) if is_prime(num)])
        elif criteria == "divisible_by_5":
            results.append([num for num in range(20, 101) if num % 5 == 0])
        else:
            results.append([])
    return results

# Test the function
criteria_list = ["odd", "even", "prime", "divisible_by_5"]
generated_values = doGenerateValues(criteria_list)

# Print the results nicely formatted
for i, criteria in enumerate(criteria_list):
    print(f"{criteria.capitalize()} Numbers from 20 to 100:")
    print(generated_values[i])
    print()

Odd Numbers from 20 to 100:
[21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]

Even Numbers from 20 to 100:
[20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]

Prime Numbers from 20 to 100:
[23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]

Divisible_by_5 Numbers from 20 to 100:
[20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]



4. write function to get middle of string and revease of length is even number
    - ABCDEF => DC
    - ABCDE => C

In [45]:
def getMiddleString(st):
    length = len(st)
    middle_index = length // 2
    
    if length % 2 == 0:  
        return st[middle_index - 1:middle_index + 1][::-1]
    else:  
        return st[middle_index]


test_strings = ["ABCDEF", "ABCDE"]

for test_str in test_strings:
    print(f"{test_str} => {getMiddleString(test_str)}")

ABCDEF => DC
ABCDE => C


5. write function to add value to middle of string if length of string is even and otherwise remove value in the middle
    - NUM => NM
    - NUME => NUAME

In [46]:
def addValueToMiddle(value):
    input_str = "NUME"  
    length = len(input_str)
    middle_index = length // 2
    
    if length % 2 == 0:  
        return input_str[:middle_index] + value + input_str[middle_index:]
    else:  
        return input_str[:middle_index] + value + input_str[middle_index:]

# Test the function
value_to_add = "A"
print(addValueToMiddle(value_to_add))


NUAME


# Working with Numpy Array

1. create numpy array of 100 values with 0

In [24]:
import numpy as np

# Create a NumPy array of 100 values initialized to 0
array_of_zeros = np.zeros(100)

print(array_of_zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


2. create numpy array of 100 values with 1

In [26]:
import numpy as np

array_of_ones = np.ones(100)
print(array_of_ones)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


3. create numpy array of 100 values with 7

In [27]:
import numpy as np

# Create an array of 100 values, each with the value 7
array_with_seven = np.full(100, 7)

print(array_with_seven)


[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


4. create numpy array of value range from 20-100

In [28]:
import numpy as np

# Create an array with values ranging from 20 to 100
array_range_20_to_100 = np.arange(20, 101)

print(array_range_20_to_100)


[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100]


5. create numpy array of identity 5x5

In [34]:
import numpy as np

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

6. resahpe below array to 5x3

In [35]:
import numpy as np

original_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

print(original_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [36]:
reshaped_array = original_array.reshape(5, 3)

print(reshaped_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


7. slicing array

In [37]:
import numpy as np

given_array = np.array([[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10],
                        [11, 12, 13, 14, 15],
                        [16, 17, 18, 19, 20],
                        [21, 22, 23, 24, 25]])
print(given_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


8. slicing array

In [38]:
sliced_array = given_array[:, 1:2]

print(sliced_array)

[[ 2]
 [ 7]
 [12]
 [17]
 [22]]


9. slicing array

In [39]:
sliced_array = given_array[1:2, 1:4]

print(sliced_array)

[[7 8 9]]


10. slicing array and transpose 

In [40]:
sliced_array = given_array[1:4, 1:2].flatten()
print(sliced_array)

[ 7 12 17]


11. slicing array and revease

In [41]:
sliced_and_reversed_array = given_array[2:3, ::-1]
print(sliced_and_reversed_array)

[[15 14 13 12 11]]


12. slicing array

In [42]:
sliced_array = given_array[1:4, 1:4]
print(sliced_array)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


13. create numpy array 10x10 with random value

In [29]:
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Generate a 10x10 array with random values between 0 and 100
arr = np.random.randint(0, 100, (10, 10))

print(arr)


[[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]
 [49  3  1  5 53  3 53 92 62 17]
 [89 43 33 73 61 99 13 94 47 14]
 [71 77 86 61 39 84 79 81 52 23]]


14. create two numpy array and multiply
    - a : numpy array must range from 1-10
    - b : numpy array must range from 11-20

In [31]:
a = np.arange(1, 10).reshape(3,3)
b = np.arange(11, 20).reshape(3,3) 

answer = np.dot(a, b)
print(answer)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


15. Create three dimension numpy array below

In [30]:
np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])