# Final Exam 29-32 Weekends

1. write function to return two result of odd and even num of list below
    - list of values from 20-100
    - [2,4,6,8,9,10]
    - [1,2,3,5,7,9]
    - [0]
    - [1]

In [50]:
def getOddEvenFromList(list):
    odd_numbers = [num for num in list if num % 2 != 0]
    even_numbers = [num for num in list if num % 2 == 0]
    print("From list: ",list, "Odd numbers:", odd_numbers, "\n\t\t\t   Even numvers: ", even_numbers)
    return [odd_numbers, even_numbers]

oddEven = getOddEvenFromList(range(20,100))
oddEven = getOddEvenFromList([2,4,6,8,9,10])
oddEven = getOddEvenFromList([0])
oddEven = getOddEvenFromList([1])

From list:  range(20, 100) Odd numbers: [21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99] 
			   Even numvers:  [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]
From list:  [2, 4, 6, 8, 9, 10] Odd numbers: [9] 
			   Even numvers:  [2, 4, 6, 8, 10]
From list:  [0] Odd numbers: [] 
			   Even numvers:  [0]
From list:  [1] Odd numbers: [1] 
			   Even numvers:  []


2. write function to reverse string below
    - James => semaJ
    - Cambodia => aidobmaC
    - National University of Management => tnemeganaM fo ytisrevinU lanoitaN

In [30]:
def getReverseString(st):
    return st[::-1]

print("James =>", getReverseString("James"))
print("Cambodia =>", getReverseString("Cambodia"))
print("National University of Management =>", "National University of Management"[::-1])

James => semaJ
Cambodia => aidobmaC
National University of Management => tnemeganaM fo ytisrevinU lanoitaN


3. write function to generate list of value below
    - All odd number from 20-100
    - All Even number from 20-100
    - All Prime number from 20-100
    - All can divid by 5 from 20-100

In [37]:
def is_prime(num):
    if num == 1:
        return False
    elif num > 1:
        for i in range(2,num):
           if (num % i) == 0:
               return False
        else:
            return True
    else:
        return False

def getOddValues(list):
    return [num for num in list if num % 2 != 0]

def getEvenValues(list):
    return [num for num in list if num % 2 == 0]

def getPrimeValues(list):
    return [num for num in list if is_prime(num)]

def getDividedValues(list, de):
    return [num for num in list if num % de == 0]


print("All odd number from 20-100:", getOddValues(range(20,100)), "\n")
print("All Even number from 20-100:", getEvenValues(range(20,100)) , "\n")
print("All Prime number from 20-100:", getPrimeValues(range(20,100)) , "\n")
print("All can divid by 5 from 20-100:", getDividedValues(range(20,100), 5) , "\n")

All odd number from 20-100: [21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99] 

All Even number from 20-100: [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98] 

All Prime number from 20-100: [23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97] 

All can divid by 5 from 20-100: [20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95] 



4. write function to get middle of string and revease of length is even number
    - ABCDEF => DC
    - ABCDE => C

In [80]:
import math as math

def getMiddleString(st):
    mid = int(len(st)/2)
    if len(st) % 2 == 0:
        return st[mid-1:mid+1]
    else:
        return st[mid]

print("ABCDEF =>", getMiddleString("ABCDEF"))
print("ABCDE =>", getMiddleString("ABCDE"))

ABCDEF => CD
ABCDE => C


5. write function to add value to middle of string if length of string is even and otherwise remove value in the middle
    - NUM => NM
    - NUME => NUAME

In [81]:
def addValueToMiddle(str, value):
    if len(str) % 2 != 0:
        return str.replace(str[int(len(str)/2)], '')
    else:
        return str[:2] + value + str[2:]

print("NUM =>", addValueToMiddle("NUM", "A"))
print("NUME =>", addValueToMiddle("NUME", "A"))

NUM => NM
NUME => NUAME


# Working with Numpy Array

1. create numpy array of 100 values with 0

In [83]:
import numpy as np

np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. create numpy array of 100 values with 1

In [84]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3. create numpy array of 100 values with 7

In [86]:
np.full(100, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

4. create numpy array of value range from 20-100

In [87]:
np.arange(20, 100)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

5. create numpy array of identity 5x5

In [88]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

6. resahpe below array to 5x3

In [110]:
a = np.arange(0, 15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [111]:
a = np.reshape(a, (5,3))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


7. slicing array

In [114]:
a = np.reshape(np.arange(1,26), (5,5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


8. slicing array

In [32]:
a[:,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

9. slicing array

In [28]:
a[1:2,1:4]

array([[7, 8, 9]])

10. slicing array and transpose 

In [142]:
arr = []
for i in a[1:4,1:2]:
    arr.append(i[0])
    
arr1 = [arr]
arr1

[[7, 12, 17]]

11. slicing array and revease

In [53]:
a[2][::-1]

array([[15, 14, 13, 12, 11]])

12. slicing array

In [54]:
a[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

13. create numpy array 10x10 with random value

[[50. 54. 69. 85. 81. 46. 85. 70. 66. 84.]
 [28. 21. 78. 53.  4. 88. 30. 46.  6. 95.]
 [57. 85.  2. 87. 72.  2. 29. 38. 55. 88.]
 [15. 34. 25. 62. 68. 34. 59. 85. 38. 34.]
 [27.  8.  2. 42. 50. 19. 81. 50. 31. 78.]
 [54. 25. 15. 90. 75. 61. 32. 47. 52. 85.]
 [65. 88. 65. 88. 73. 23. 83. 64. 22. 58.]
 [31. 81. 39.  3. 79. 11. 80. 97. 46. 94.]
 [80. 90. 23.  4. 20. 85. 83. 91. 98. 88.]
 [ 9.  2. 30. 72. 70. 39. 24. 35. 15. 27.]]


In [145]:
np.floor(100*np.random.random((10,10)))

array([[35., 61., 68., 34., 52., 17., 36., 45., 17.,  4.],
       [95., 96., 59., 42., 29., 91., 15.,  5., 51., 58.],
       [90., 70., 46., 95., 66., 71., 32., 90., 81., 91.],
       [40., 47., 81.,  2., 53., 15., 76., 67., 56., 45.],
       [44., 52., 92., 95., 17., 71., 47.,  4., 95., 44.],
       [56., 46., 69., 50., 31., 50., 15.,  5., 29., 78.],
       [16., 96.,  2., 37.,  4., 86., 87., 97., 22., 69.],
       [27., 90., 21.,  8., 38., 19., 31., 14., 99., 64.],
       [51., 18., 88., 69., 91., 14., 37., 37., 13., 12.],
       [19., 80., 76., 88., 10., 55., 30., 27., 13., 16.]])

14. create two numpy array and multiply
    - a : numpy array must range from 1-10
    - b : numpy array must range from 11-20

In [40]:
c = np.reshape(np.arange(1,10), (3,3))

d = np.reshape(np.arange(11,20), (3,3))

np.dot(c,d)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


15. Create three dimension numpy array below

In [35]:
a = np.range()

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [165]:
e = np.reshape(np.arange(1,7), (2,3))
f = np.reshape(np.arange(7,13), (2,3))

[e,f]

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]