# Final Exam 29-32 Weekends

1. write function to return two result of odd and even num of list below
    - list of values from 20-100
    - [2,4,6,8,9,10]
    - [1,2,3,5,7,9]
    - [0]
    - [1]

In [1]:
def getOddEvenFromList(lst):
    return

2. write function to reverse string below
    - James => semaJ
    - Cambodia => aidobmaC
    - National University of Management => tnemeganaM fo ytisrevinU lanoitaN

In [41]:
def getReverseString(st):
    return st[::-1]
print ("James =>" ,getReverseString("semaJ"))
print ("Cambodia =>" ,getReverseString("aidobmaC"))
print ("National University of Management =>" ,getReverseString("tnemeganaM fo ytisrevinU lanoitaN"[::-1]))


James => James
Cambodia => Cambodia
National University of Management => tnemeganaM fo ytisrevinU lanoitaN


3. write function to generate list of value below
    - All odd number from 20-100
    - All Even number from 20-100
    - All Prime number from 20-100
    - All can divid by 5 from 20-100

In [8]:
def doGenerateValues(lst):
    return

4. write function to get middle of string and revease of length is even number
    - ABCDEF => DC
    - ABCDE => C

5. write function to add value to middle of string if length of string is even and otherwise remove value in the middle
    - NUM => NM
    - NUME => NUAME

In [10]:
def addValueToMiddle(value):
    return

# Working with Numpy Array

1. create numpy array of 100 values with 0

In [3]:
import numpy as np
import random as rd

In [4]:
y = np.zeros((10,10))
print(y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


2. create numpy array of 100 values with 1

In [5]:
y = np.ones((10,10))
print (y)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


3. create numpy array of 100 values with 7

In [9]:
y = np.full((10,10),7)
print (y)

[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


4. create numpy array of value range from 20-100

In [11]:
y = np.arange(20,101)
print(y)

[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100]


5. create numpy array of identity 5x5

6. resahpe below array to 5x3

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
a = np.arange(0,15)
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
b = a.reshape((5,3))
print (b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


7. slicing array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [21]:
x = np.arange(1,26)


In [22]:
y = x.reshape((5,5))
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


8. slicing array

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [26]:
a = np.reshape(np.arange(1,26), (5,5))

In [27]:
a[:,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

9. slicing array

array([[7, 8, 9]])

In [28]:
a[1:2,1:4]

array([[7, 8, 9]])

10. slicing array and transpose 

11. slicing array and revease

array([[15, 14, 13, 12, 11]])

In [32]:
a[2][::-1]

array([15, 14, 13, 12, 11])

12. slicing array

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [33]:
a[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

13. create numpy array 10x10 with random value

[[50. 54. 69. 85. 81. 46. 85. 70. 66. 84.]
 [28. 21. 78. 53.  4. 88. 30. 46.  6. 95.]
 [57. 85.  2. 87. 72.  2. 29. 38. 55. 88.]
 [15. 34. 25. 62. 68. 34. 59. 85. 38. 34.]
 [27.  8.  2. 42. 50. 19. 81. 50. 31. 78.]
 [54. 25. 15. 90. 75. 61. 32. 47. 52. 85.]
 [65. 88. 65. 88. 73. 23. 83. 64. 22. 58.]
 [31. 81. 39.  3. 79. 11. 80. 97. 46. 94.]
 [80. 90. 23.  4. 20. 85. 83. 91. 98. 88.]
 [ 9.  2. 30. 72. 70. 39. 24. 35. 15. 27.]]


In [35]:
np.floor(100*np.random.random((10,10)))

array([[38., 71., 34., 32., 65., 24., 44., 36., 42., 57.],
       [ 6., 89., 48., 67., 83., 10., 56., 19., 31., 80.],
       [85., 65., 48., 24., 18., 38., 56., 88., 51., 14.],
       [43.,  8., 86., 80., 22., 23., 67., 41., 46., 44.],
       [ 5., 72., 61., 43., 42., 17., 92., 73., 99., 34.],
       [23., 30., 66., 60.,  6.,  2., 52., 34., 57., 70.],
       [94., 28., 64., 87., 52., 74., 54., 80., 29., 79.],
       [26.,  1., 90.,  7., 11., 78., 19., 53.,  8., 74.],
       [46.,  1., 89., 81., 76., 66., 18., 81., 13., 43.],
       [71., 17., 25., 73., 11., 90., 77., 82., 60., 88.]])

14. create two numpy array and multiply
    - a : numpy array must range from 1-10
    - b : numpy array must range from 11-20

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [37]:
d = np.reshape(np.arange(1,10),(3,3))
e = np.reshape(np.arange(11,20),(3,3))
np.dot(d,e)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

15. Create three dimension numpy array below

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [34]:
y = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    ])
print (y)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
