# Final Exam 29-32 Weekends

1. write function to return two result of odd and even num of list below
    - list of values from 20-100
    - [2,4,6,8,9,10]
    - [1,2,3,5,7,9]
    - [0]
    - [1]

In [97]:
def separate_odd_even(numbers):
  even_numbers = []
  odd_numbers = []

  for num in numbers:
    if num % 2 == 0:
      even_numbers.append(num)
    else:
      odd_numbers.append(num)
  return even_numbers, odd_numbers

for numbers in [list1]:
  even_numbers, odd_numbers = separate_odd_even(numbers)
  print(f"Original list: {numbers}")
  print(f"Even numbers: {even_numbers}")
  print(f"Odd numbers: {odd_numbers}")
  print()


Original list: range(20, 101)
Even numbers: [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
Odd numbers: [21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]



2. write function to reverse string below
    - James => semaJ
    - Cambodia => aidobmaC
    - National University of Management => tnemeganaM fo ytisrevinU lanoitaN

In [98]:
def reverse_string(text):

  # Check if the input is a string
  if not isinstance(text, str):
    raise TypeError("Input must be a string.")

  # Handle empty string or whitespace-only string
  if not text.strip():
    return text

  # Use slicing for efficient reversal
  return text[::-1]

# Test cases
strings = ["James", "Cambodia", "National University of Management"]
for text in strings:
  reversed_text = reverse_string(text)

  print(f"{text} -> {reversed_text}")

James -> semaJ
Cambodia -> aidobmaC
National University of Management -> tnemeganaM fo ytisrevinU lanoitaN


3. write function to generate list of value below
    - All odd number from 20-100
    - All Even number from 20-100
    - All Prime number from 20-100
    - All can divid by 5 from 20-100

In [99]:
def generate_number_lists(start, end):
  odd_numbers = []
  even_numbers = []
  prime_numbers = []
  divide_by_5 = []

  for num in range(start, end + 1):
    if num % 2 == 0:
      even_numbers.append(num)
    else:
      odd_numbers.append(num)

    # Check condition
    if num > 2 and all(num % i != 0 for i in range(3, int(num**0.5) + 1, 2)):
      prime_numbers.append(num)

    if num % 5 == 0:
      divide_by_5.append(num)

  return {
      "odd_numbers": odd_numbers,
      "even_numbers": even_numbers,
      "prime_numbers": prime_numbers,
      "divide_by_5": divide_by_5,
  }

#print the lists
number_lists = generate_number_lists(20, 100)
for key, value in number_lists.items():
  print(f"{key}: {value}")

odd_numbers: [21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
even_numbers: [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
prime_numbers: [20, 22, 23, 26, 28, 29, 31, 32, 34, 37, 38, 41, 43, 44, 46, 47, 52, 53, 58, 59, 61, 62, 64, 67, 68, 71, 73, 74, 76, 79, 82, 83, 86, 88, 89, 92, 94, 97]
divide_by_5: [20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


4. write function to get middle of string and revease of length is even number
    - ABCDEF => DC
    - ABCDE => C

In [100]:
def get_middle_of_string(text):
  if not text:
    return ""

  mid_index = len(text) // 2
  if len(text) % 2 == 0:
    return text[mid_index - 1:mid_index + 1][::-1]
  else:
    return text[mid_index]

# print
strings = ["ABCDEF", "ABCDE"]
for text in strings:
  middle = get_middle_of_string(text)
  print(f"Original string: {text}")
  print(f"Middle character(s): {middle}")
  print()

Original string: ABCDEF
Middle character(s): DC

Original string: ABCDE
Middle character(s): C



5. write function to add value to middle of string if length of string is even and otherwise remove value in the middle
    - NUM => NM
    - NUME => NUAME

In [101]:
def modify_middle_of_string(text, value):

   if not text:
       raise ValueError("Input string cannot be empty.")
   if not value:
       raise ValueError("Value to add cannot be empty.")

   mid_index = len(text) // 2
   if len(text) % 2 == 0:
      
       return text[:mid_index] + value + text[mid_index + 1:][::-1]
   else:
       return text[:mid_index] + text[mid_index + 1:]

strings = ["NUM", "NUME"]
values = ["M", "A", "", " "]
for text, value in zip(strings, values):
       modified_text = modify_middle_of_string(text, value)
       print(f"Original string: {text}")
       print(f"Modified string: {modified_text}")


Original string: NUM
Modified string: NM
Original string: NUME
Modified string: NUAE


# Working with Numpy Array

1. create numpy array of 100 values with 0

In [102]:
import numpy as np
array = np.array([0] * 100)
print(array)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


2. create numpy array of 100 values with 1

In [103]:
array = np.array([1] * 100)
print(array)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


3. create numpy array of 100 values with 7

In [104]:
array = np.array([7] * 100)
print(array)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


4. create numpy array of value range from 20-100

In [35]:
array = np.array([i for i in range(20, 101)])
print(array)

[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100]


5. create numpy array of identity 5x5

In [36]:
identity_matrix = np.zeros((5, 5))
identity_matrix[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]] = 1
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


6. resahpe below array to 5x3

In [37]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
reshaped_array = np.reshape(array[:15], (5, 3))
print(reshaped_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


7. slicing array

In [41]:
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


8. slicing array

In [45]:
result = array[:, 1:2]

print(result)


[[ 2]
 [ 7]
 [12]
 [17]
 [22]]


9. slicing array

In [52]:
result = array[1:2,1:4]
print(result)

[[7 8 9]]


10. slicing array and transpose 

In [95]:
result = array[1:4, 1:2].flatten()
print(result)

[ 7 12 17]


11. slicing array and revease

In [71]:
result = array[-3, ::-1]
print(result)

[15 14 13 12 11]


12. slicing array

In [72]:
result = array[1:4, 1:4]
print(result)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


13. create numpy array 10x10 with random value

In [74]:
random_array = np.random.randint(0, 101, size=(10, 10))
print(random_array)

[[ 12  75  26  35  40   8  90  82  89  13]
 [ 79  38  50  22  37  54   0   1  16  75]
 [ 40  38  30  42  52  45   3  68  56  25]
 [ 26  59  62  33  24  49   8  69  83  90]
 [ 69   6   6  99  53  37  90  69  94  16]
 [ 97 100  37  83  34  80  74  44  10  13]
 [ 81  28  44  62  50   8  60  53  41  80]
 [ 16  12  37   3  72  31  57  90   7  64]
 [100  13  26  77  96  43  55  99  88  77]
 [ 25  22  26  64  90   0  21  43  63  58]]


14. create two numpy array and multiply
    - a : numpy array must range from 1-10
    - b : numpy array must range from 11-20

In [88]:
a = np.arange(1, 10).reshape(3,3)
b = np.arange(11, 20).reshape(3,3) 

answer = np.dot(a, b)
print(answer)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


15. Create three dimension numpy array below

In [89]:
np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])