# Final Exam 29-32 Weekends

1. write function to return two result of odd and even num of list below
    - list of values from 20-100
    - [2,4,6,8,9,10]
    - [1,2,3,5,7,9]
    - [0]
    - [1]

In [1]:
def getOddEvenFromList(lst):
    return

2. write function to reverse string below
    - James => semaJ
    - Cambodia => aidobmaC
    - National University of Management => tnemeganaM fo ytisrevinU lanoitaN

In [7]:
def getReverseString(st):
    return

3. write function to generate list of value below
    - All odd number from 20-100
    - All Even number from 20-100
    - All Prime number from 20-100
    - All can divid by 5 from 20-100

In [8]:
def doGenerateValues(lst):
    return

4. write function to get middle of string and revease of length is even number
    - ABCDEF => DC
    - ABCDE => C

In [9]:
def getMiddleString(st):
    return

5. write function to add value to middle of string if length of string is even and otherwise remove value in the middle
    - NUM => NM
    - NUME => NUAME

In [10]:
def addValueToMiddle(value):
    return

# Working with Numpy Array

1. create numpy array of 100 values with 0

2. create numpy array of 100 values with 1

3. create numpy array of 100 values with 7

4. create numpy array of value range from 20-100

5. create numpy array of identity 5x5

6. resahpe below array to 5x3

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


7. slicing array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


8. slicing array

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

9. slicing array

array([[7, 8, 9]])

10. slicing array and transpose 

array([[ 7, 12, 17]])

11. slicing array and revease

array([[15, 14, 13, 12, 11]])

12. slicing array

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

13. create numpy array 10x10 with random value

[[50. 54. 69. 85. 81. 46. 85. 70. 66. 84.]
 [28. 21. 78. 53.  4. 88. 30. 46.  6. 95.]
 [57. 85.  2. 87. 72.  2. 29. 38. 55. 88.]
 [15. 34. 25. 62. 68. 34. 59. 85. 38. 34.]
 [27.  8.  2. 42. 50. 19. 81. 50. 31. 78.]
 [54. 25. 15. 90. 75. 61. 32. 47. 52. 85.]
 [65. 88. 65. 88. 73. 23. 83. 64. 22. 58.]
 [31. 81. 39.  3. 79. 11. 80. 97. 46. 94.]
 [80. 90. 23.  4. 20. 85. 83. 91. 98. 88.]
 [ 9.  2. 30. 72. 70. 39. 24. 35. 15. 27.]]


14. create two numpy array and multiply
    - a : numpy array must range from 1-10
    - b : numpy array must range from 11-20

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


15. Create three dimension numpy array below

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
